import type { Metadata } from "next";

// Components
import { ConfigProvider } from "antd";
import { AuthProvider } from "@/contexts/AuthContext";

// Theme
import theme from "./theme.config";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ConfigProvider theme={theme}>
            {children}
          </ConfigProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
